# Generated by Django 5.0.3 on 2024-03-08 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinemas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default='manager', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('movie', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('trailer', models.CharField(default='null', max_length=200)),
                ('date', models.CharField(default='null', max_length=20)),
                ('movi_desc', models.TextField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('poster', models.ImageField(default='movi/poster/not.jpg', upload_to='movi/poster')),
                ('genre', models.CharField(default='Action | Romance | comdey', max_length=50)),
                ('duration', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.ImageField(default='movi/navbar/not.jpg', upload_to='movi/navbar')),
            ],
        ),
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('cinema', models.AutoField(primary_key=True, serialize=False)),
                ('role', models.CharField(default='manager', max_length=30)),
                ('movi_name', models.CharField(max_length=100)),
                ('poster', models.ImageField(default='movi/navbar/not.jpg', upload_to='movi/navbar')),
                ('screen', models.CharField(default='null', max_length=10)),
                ('phoneno', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('adress', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('shows', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=50)),
                ('date', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('cinema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinema_shows', to='moviapp.cinema')),
                ('movi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movi_shows', to='moviapp.movie')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('shows', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moviapp.show')),
            ],
        ),
    ]
